orbs:
  docker: circleci/docker@1.4.0
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
#          remote-docker-dlc: true
#          not allow free-plan
          path: src/frontend
          tag: << pipeline.git.revision >>
          use-remote-docker: true
