version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest ./src/frontend
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master